[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[lint]
exclude_lints=[
    "screaming-snake-case-immutable",
    "mixed-case-variable",
    "mixed-case-function"
]

[etherscan]
mainnet= { key = "${ETHERSCAN_KEY}", chain = 1 }

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"