[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[lint]
exclude_lints=[
    "screaming-snake-case-immutable",
    "mixed-case-variable",
    "mixed-case-function"
]

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}", chain = 1 }
tenderly = { key = "${TENDERLY_ACCESS_KEY}", url = "${TENDERLY_VERIFIER_URL}" }


[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
tenderly = "${TENDERLY_VIRTUAL_TESTNET_RPC}"