[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
sizes = true
fs_permissions = [
    { access = "read", path = "./broadcast" },
]

[lint]
exclude_lints=[
    "screaming-snake-case-immutable",
    "mixed-case-variable",
    "mixed-case-function"
]

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}", chain = 1 }
tenderly = { key = "${TENDERLY_ACCESS_KEY}", chain =1,  url = "${TENDERLY_VERIFIER_URL}" }


[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
tenderly = "${TENDERLY_VIRTUAL_TESTNET_RPC}"
